# This is a basic workflow to help you get started with Actions

name: CI_tag

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git clone https://github.com/google/googletest.git
          cd googletest
          cmake .
          cmake --build .
          sudo make install
      - run: |
          cmake .
          cmake --build .
          cmake --build . --target test
          cmake --build . --target package
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./SR2-1-Linux.deb
          asset_name: SR2-1-Linux.deb
          asset_content_type: application/vnd.debian.binary-package
